package gui.inputPanels;

import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public interface Configurator {
	
	/**
	 * Return a list of Elements created by this node reflecting the proper XML structure, suitable
	 * for handing directly to an ACGDocumentBuilder
	 * @param doc The Document needed to create new Elements
	 * @return
	 * @throws ParserConfigurationException 
	 * @throws InputConfigException
	 */
	public Element[] getRootXMLNodes(Document doc) throws ParserConfigurationException, InputConfigException;
	
	/**
	 * Return a list of Parameters generated by the most recent call to getRootXMLNodes, or null if there has
	 * been no call yet to getRootXMLNodes
	 * @return
	 */
	public Element[] getParameters();
	
	/**
	 * Return a list of Likelihoods generated by the most recent call to getRootXMLNodes, or null if there has
	 * been no call yet to getRootXMLNodes
	 * @return
	 */	
	public Element[] getLikelihoods();
	
	class InputConfigException extends Exception {
		
		public InputConfigException(String message) {
			super(message);
		}
	}
}
